/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrn.peoo.apresentacao;

import br.edu.ifrn.peoo.excecoes.ContatoJaCadastradoException;
import br.edu.ifrn.peoo.excecoes.ContatoNaoEncontradoException;
import br.edu.ifrn.peoo.excecoes.ParametroVazioException;
import br.edu.ifrn.peoo.logica.Agenda;
import br.edu.ifrn.peoo.persistencia.Persistencia;
import br.edu.ifrn.peoo.modelo.Pessoa;
import br.edu.ifrn.peoo.modelo.PessoaFisica;
import br.edu.ifrn.peoo.modelo.PessoaJuridica;
import java.beans.XMLDecoder;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import java.beans.XMLEncoder;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Arthur Cruz
 */
public class View extends javax.swing.JFrame {

    Agenda agenda;
    DefaultTableModel model;

    public void listarNaTabela() {
        model = (DefaultTableModel) tabelaPessoas.getModel();
        Object rowData[] = new Object[9];
        model.setRowCount(0);
        for (int i = 0; i < agenda.listarContatos().size(); i++) {
            rowData[0] = agenda.listarContatos().get(i).getNome();
            rowData[1] = agenda.listarContatos().get(i).getTelefone();
            rowData[2] = agenda.listarContatos().get(i).getEndereco();
            rowData[3] = agenda.listarContatos().get(i).getCidade();
            rowData[4] = agenda.listarContatos().get(i).getEstado();
            if (agenda.listarContatos().get(i) instanceof PessoaFisica) {
                PessoaFisica pF = (PessoaFisica) agenda.listarContatos().get(i);
                rowData[5] = pF.getCpf();
                rowData[6] = "";
                rowData[7] = "";
                rowData[8] = "";
            }
            if (agenda.listarContatos().get(i) instanceof PessoaJuridica) {
                PessoaJuridica pJ = (PessoaJuridica) agenda.listarContatos().get(i);
                rowData[5] = "";
                rowData[6] = pJ.getCnpj();
                rowData[7] = pJ.getRazaoSocial();
                rowData[8] = pJ.getNomeFantasia();
            }
            model.addRow(rowData);
        }
    }

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        agenda = new Agenda();
        listarNaTabela();
        //agenda.setListaContatos(Persistencia.getListFromXML());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPessoaFisicaJuridica = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnTelaCadastro = new javax.swing.JButton();
        btnTelaListar = new javax.swing.JButton();
        btnTelaRemover = new javax.swing.JButton();
        btnTelaBuscar = new javax.swing.JButton();
        btnTelaTotal = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        painelInicio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        painelCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radioBtnPf = new javax.swing.JRadioButton();
        radioBtnPj = new javax.swing.JRadioButton();
        painelTxtFieldGroup = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        formattedTxtTelefone = new javax.swing.JFormattedTextField();
        txtEndereco = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        comboBoxEstados = new javax.swing.JComboBox<>();
        formattedTxtCpf = new javax.swing.JFormattedTextField();
        formattedTxtCnpj = new javax.swing.JFormattedTextField();
        txtRazaoSocial = new javax.swing.JTextField();
        txtNomeFantasia = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        painelListar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPessoas = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        lblTituloListaRemove = new javax.swing.JLabel();
        btnRemover = new javax.swing.JButton();
        painelBuscar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnResultadoBuscar = new javax.swing.JButton();
        lblResultadoBuscar = new javax.swing.JLabel();
        painelTotalizadores = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblListarTot = new javax.swing.JLabel();
        btnListarTot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 100));
        setSize(new java.awt.Dimension(600, 400));

        jPanel1.setLayout(new java.awt.GridLayout(6, 1, 1, 1));

        btnTelaCadastro.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnTelaCadastro.setText("Cadastrar");
        btnTelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(btnTelaCadastro);

        btnTelaListar.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnTelaListar.setText("Listar");
        btnTelaListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaListarActionPerformed(evt);
            }
        });
        jPanel1.add(btnTelaListar);

        btnTelaRemover.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnTelaRemover.setText("Remover");
        btnTelaRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaRemoverActionPerformed(evt);
            }
        });
        jPanel1.add(btnTelaRemover);

        btnTelaBuscar.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnTelaBuscar.setText("Buscar");
        btnTelaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnTelaBuscar);

        btnTelaTotal.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnTelaTotal.setText("Total");
        btnTelaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaTotalActionPerformed(evt);
            }
        });
        jPanel1.add(btnTelaTotal);

        btnInicio.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnInicio.setText("Início");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicio);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setLayout(new java.awt.CardLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/peoo/imagens/imageicon.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Agenda");

        javax.swing.GroupLayout painelInicioLayout = new javax.swing.GroupLayout(painelInicio);
        painelInicio.setLayout(painelInicioLayout);
        painelInicioLayout.setHorizontalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelInicioLayout.setVerticalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInicioLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(painelInicio, "card3");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Pessoa");

        buttonGroupPessoaFisicaJuridica.add(radioBtnPf);
        radioBtnPf.setSelected(true);
        radioBtnPf.setText("Pessoa Física");
        radioBtnPf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                radioBtnPfFocusGained(evt);
            }
        });
        radioBtnPf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnPfActionPerformed(evt);
            }
        });

        buttonGroupPessoaFisicaJuridica.add(radioBtnPj);
        radioBtnPj.setText("Pessoa Jurídica");
        radioBtnPj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnPjActionPerformed(evt);
            }
        });

        painelTxtFieldGroup.setLayout(new java.awt.GridLayout(9, 0, 0, 7));

        txtNome.setText("Nome...");
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        painelTxtFieldGroup.add(txtNome);

        formattedTxtTelefone.setText("Telefone...");
        formattedTxtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formattedTxtTelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formattedTxtTelefoneFocusLost(evt);
            }
        });
        painelTxtFieldGroup.add(formattedTxtTelefone);

        txtEndereco.setText("Endereço...");
        txtEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEnderecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEnderecoFocusLost(evt);
            }
        });
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        painelTxtFieldGroup.add(txtEndereco);

        txtCidade.setText("Cidade...");
        txtCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCidadeFocusLost(evt);
            }
        });
        painelTxtFieldGroup.add(txtCidade);

        comboBoxEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Paraná", "Paraíba", "Pará", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondonia", "Roraima", "Santa Catarina", "Sergipe", "São Paulo", "Tocantins" }));
        painelTxtFieldGroup.add(comboBoxEstados);

        formattedTxtCpf.setText("CPF...");
        formattedTxtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formattedTxtCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formattedTxtCpfFocusLost(evt);
            }
        });
        painelTxtFieldGroup.add(formattedTxtCpf);

        formattedTxtCnpj.setText("CNPJ...");
        formattedTxtCnpj.setEnabled(false);
        formattedTxtCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formattedTxtCnpjFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formattedTxtCnpjFocusLost(evt);
            }
        });
        painelTxtFieldGroup.add(formattedTxtCnpj);

        txtRazaoSocial.setText("Razão Social...");
        txtRazaoSocial.setEnabled(false);
        txtRazaoSocial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRazaoSocialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRazaoSocialFocusLost(evt);
            }
        });
        painelTxtFieldGroup.add(txtRazaoSocial);

        txtNomeFantasia.setText("Nome Fantasia...");
        txtNomeFantasia.setEnabled(false);
        txtNomeFantasia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFantasiaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFantasiaFocusLost(evt);
            }
        });
        txtNomeFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFantasiaActionPerformed(evt);
            }
        });
        painelTxtFieldGroup.add(txtNomeFantasia);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCadastroLayout = new javax.swing.GroupLayout(painelCadastro);
        painelCadastro.setLayout(painelCadastroLayout);
        painelCadastroLayout.setHorizontalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(painelTxtFieldGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelCadastroLayout.createSequentialGroup()
                            .addComponent(radioBtnPf)
                            .addGap(82, 82, 82)
                            .addComponent(radioBtnPj)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroLayout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addGap(102, 102, 102)))
                .addGap(153, 153, 153))
        );
        painelCadastroLayout.setVerticalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnPf)
                    .addComponent(radioBtnPj))
                .addGap(18, 18, 18)
                .addComponent(painelTxtFieldGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrar)
                .addGap(25, 25, 25))
        );

        jPanel2.add(painelCadastro, "card2");
        setResizable(false);

        tabelaPessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Telefone", "Endereço", "Cidade", "Estado", "CPF", "CNPJ", "Razão Social", "Nome Fantasia"
            }
        ));
        jScrollPane1.setViewportView(tabelaPessoas);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        lblTituloListaRemove.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTituloListaRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloListaRemove.setText("Listar Pessoas");

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelListarLayout = new javax.swing.GroupLayout(painelListar);
        painelListar.setLayout(painelListarLayout);
        painelListarLayout.setHorizontalGroup(
            painelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addComponent(lblTituloListaRemove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelListarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelListarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover)))
                .addGap(240, 240, 240))
        );
        painelListarLayout.setVerticalGroup(
            painelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloListaRemove)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.add(painelListar, "card4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Buscar");

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnResultadoBuscar.setText("Buscar pessoa");
        btnResultadoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoBuscarActionPerformed(evt);
            }
        });

        lblResultadoBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblResultadoBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painelBuscarLayout = new javax.swing.GroupLayout(painelBuscar);
        painelBuscar.setLayout(painelBuscarLayout);
        painelBuscarLayout.setHorizontalGroup(
            painelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBuscarLayout.createSequentialGroup()
                        .addGap(0, 141, Short.MAX_VALUE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addComponent(lblResultadoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnResultadoBuscar)
                .addGap(237, 237, 237))
        );
        painelBuscarLayout.setVerticalGroup(
            painelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(104, 104, 104)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(lblResultadoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResultadoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jPanel2.add(painelBuscar, "card5");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Listar Totalizadores");

        lblListarTot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblListarTot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnListarTot.setText("Listar");
        btnListarTot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarTotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelTotalizadoresLayout = new javax.swing.GroupLayout(painelTotalizadores);
        painelTotalizadores.setLayout(painelTotalizadoresLayout);
        painelTotalizadoresLayout.setHorizontalGroup(
            painelTotalizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblListarTot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTotalizadoresLayout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(btnListarTot)
                .addGap(256, 256, 256))
        );
        painelTotalizadoresLayout.setVerticalGroup(
            painelTotalizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTotalizadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(109, 109, 109)
                .addComponent(lblListarTot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(btnListarTot, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        jPanel2.add(painelTotalizadores, "card6");

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);
        setResizable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioBtnPfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnPfActionPerformed
        formattedTxtCpf.setEnabled(true);
        formattedTxtCnpj.setEnabled(false);
        txtNomeFantasia.setEnabled(false);
        txtRazaoSocial.setEnabled(false);
    }//GEN-LAST:event_radioBtnPfActionPerformed

    private void btnTelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaCadastroActionPerformed
        painelCadastro.setVisible(true);
        painelInicio.setVisible(false);
        painelListar.setVisible(false);
        painelBuscar.setVisible(false);
        painelTotalizadores.setVisible(false);
    }//GEN-LAST:event_btnTelaCadastroActionPerformed

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        if (txtNome.getText().equals("Nome...")) {
            txtNome.setText("");
        }
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add yourandling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        if (txtNome.getText().equals("")) {
            txtNome.setText("Nome...");
        }
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtEnderecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnderecoFocusGained
        if (txtEndereco.getText().equals("Endereço...")) {
            txtEndereco.setText("");
        }
    }//GEN-LAST:event_txtEnderecoFocusGained

    private void txtEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnderecoFocusLost
        if (txtEndereco.getText().equals("")) {
            txtEndereco.setText("Endereço...");
        }
    }//GEN-LAST:event_txtEnderecoFocusLost

    private void txtCidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCidadeFocusGained
        if (txtCidade.getText().equals("Cidade...")) {
            txtCidade.setText("");
        }
    }//GEN-LAST:event_txtCidadeFocusGained

    private void txtCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCidadeFocusLost
        if (txtCidade.getText().equals("")) {
            txtCidade.setText("Cidade...");
        }
    }//GEN-LAST:event_txtCidadeFocusLost

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void formattedTxtTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formattedTxtTelefoneFocusGained
        if (formattedTxtTelefone.getText().equals("Telefone...")) {
            formattedTxtTelefone.setText("");
            MaskFormatter format = null;
            try {
                format = new MaskFormatter("(##) #####-####");
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
            formattedTxtTelefone.setFormatterFactory(new DefaultFormatterFactory(format));
        }
    }//GEN-LAST:event_formattedTxtTelefoneFocusGained

    private void formattedTxtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formattedTxtTelefoneFocusLost
        if (formattedTxtTelefone.getText().equals("(  )      -    ")) {
            formattedTxtTelefone.setFormatterFactory(null);
            formattedTxtTelefone.setText("Telefone...");
        }
    }//GEN-LAST:event_formattedTxtTelefoneFocusLost

    private void formattedTxtCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formattedTxtCpfFocusGained
        if (formattedTxtCpf.getText().equals("CPF...")) {
            formattedTxtCpf.setText("");
            MaskFormatter format = null;
            try {
                format = new MaskFormatter("###.###.###-##");
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
            formattedTxtCpf.setFormatterFactory(new DefaultFormatterFactory(format));
        }
    }//GEN-LAST:event_formattedTxtCpfFocusGained

    private void formattedTxtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formattedTxtCpfFocusLost
        //   .   .   -  
        if (formattedTxtCpf.getText().equals("   .   .   -  ")) {
            formattedTxtCpf.setFormatterFactory(null);
            formattedTxtCpf.setText("CPF...");
        }
    }//GEN-LAST:event_formattedTxtCpfFocusLost

    private void formattedTxtCnpjFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formattedTxtCnpjFocusGained
        if (formattedTxtCnpj.getText().equals("CNPJ...")) {
            formattedTxtCnpj.setText("");
            MaskFormatter format = null;
            try {
                format = new MaskFormatter("##.###.###/0001-##");
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
            formattedTxtCnpj.setFormatterFactory(new DefaultFormatterFactory(format));
        }
    }//GEN-LAST:event_formattedTxtCnpjFocusGained

    private void formattedTxtCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formattedTxtCnpjFocusLost
        //  .   .   /0001-  
        if (formattedTxtCnpj.getText().equals("  .   .   /0001-  ")) {
            formattedTxtCnpj.setFormatterFactory(null);
            formattedTxtCnpj.setText("CNPJ...");
        }
    }//GEN-LAST:event_formattedTxtCnpjFocusLost

    private void txtNomeFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFantasiaActionPerformed

    private void txtRazaoSocialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRazaoSocialFocusGained
        if (txtRazaoSocial.getText().equals("Razão Social...")) {
            txtRazaoSocial.setText("");
        }
    }//GEN-LAST:event_txtRazaoSocialFocusGained

    private void txtRazaoSocialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRazaoSocialFocusLost
        if (txtRazaoSocial.getText().equals("")) {
            txtRazaoSocial.setText("Razão Social...");
        }
    }//GEN-LAST:event_txtRazaoSocialFocusLost

    private void txtNomeFantasiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFantasiaFocusGained
        if (txtNomeFantasia.getText().equals("Nome Fantasia...")) {
            txtNomeFantasia.setText("");
        }
    }//GEN-LAST:event_txtNomeFantasiaFocusGained

    private void txtNomeFantasiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFantasiaFocusLost
        if (txtNomeFantasia.getText().equals("")) {
            txtNomeFantasia.setText("Nome Fantasia...");
        }
    }//GEN-LAST:event_txtNomeFantasiaFocusLost

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Pessoa pessoa = null;
        //Condição para cadastrar pessoa física:
        if (radioBtnPf.isSelected()) {
            if (!txtNome.getText().equals("Nome...") && !txtEndereco.getText().equals("Endereço...") && !formattedTxtTelefone.equals("Telefone...") && !txtCidade.getText().equals("Cidade...") && !formattedTxtCpf.getText().equals("CPF...")) {
                pessoa = new PessoaFisica(txtNome.getText(),
                        formattedTxtTelefone.getText(),
                        txtEndereco.getText(),
                        txtCidade.getText(),
                        comboBoxEstados.getSelectedItem().toString(),
                        formattedTxtCpf.getText());
            }
        }
        //Condição para cadastrar pessoa jurídica:
        if (radioBtnPj.isSelected()) {
            if (!txtNome.getText().equals("Nome...") && !txtEndereco.getText().equals("Endereço...") && !formattedTxtTelefone.equals("Telefone...") && !txtCidade.getText().equals("Cidade...") && !formattedTxtCnpj.getText().equals("CNPJ...") && !txtRazaoSocial.getText().equals("Razão Social...") && !txtNomeFantasia.equals("Nome Fantasia...")) {
                pessoa = new PessoaJuridica(txtNome.getText(),
                        formattedTxtTelefone.getText(),
                        txtEndereco.getText(),
                        txtCidade.getText(),
                        comboBoxEstados.getSelectedItem().toString(),
                        formattedTxtCnpj.getText(),
                        txtRazaoSocial.getText(),
                        txtNomeFantasia.getText());
            }
        }
        try {
            agenda.adicionar(pessoa);
            //Persistencia.convertListToXML(agenda.listarContatos());
        } catch (ContatoJaCadastradoException | ParametroVazioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        System.out.println("-----------------------");
        for (Pessoa p : agenda.listarContatos()) {
            System.out.println(p);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void radioBtnPfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_radioBtnPfFocusGained
        //
    }//GEN-LAST:event_radioBtnPfFocusGained

    private void radioBtnPjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnPjActionPerformed
        formattedTxtCpf.setEnabled(false);
        formattedTxtCnpj.setEnabled(true);
        txtNomeFantasia.setEnabled(true);
        txtRazaoSocial.setEnabled(true);
    }//GEN-LAST:event_radioBtnPjActionPerformed

    private void btnTelaListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaListarActionPerformed
        painelListar.setVisible(true);
        painelCadastro.setVisible(false);
        painelInicio.setVisible(false);
        painelBuscar.setVisible(false);
        painelTotalizadores.setVisible(false);
        btnRemover.setVisible(false);
        btnListar.setVisible(true);
        //txtRemover.setVisible(false);
        lblTituloListaRemove.setText("Listar Pessoas");
    }//GEN-LAST:event_btnTelaListarActionPerformed
//https://www.youtube.com/watch?v=H-aTpt4NG-s
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listarNaTabela();

    }//GEN-LAST:event_btnListarActionPerformed

    private void btnTelaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaBuscarActionPerformed
        painelBuscar.setVisible(true);
        painelCadastro.setVisible(false);
        painelInicio.setVisible(false);
        painelListar.setVisible(false);
        painelTotalizadores.setVisible(false);
    }//GEN-LAST:event_btnTelaBuscarActionPerformed

    private void btnResultadoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoBuscarActionPerformed
        try {
            JOptionPane.showMessageDialog(null, agenda.buscar(txtBuscar.getText()).toString());
        } catch (ContatoNaoEncontradoException | ParametroVazioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnResultadoBuscarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (!tabelaPessoas.getSelectionModel().isSelectionEmpty()) {
            int input = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover?");
            if (input == 0) {
                try {
                    String user = (String) model.getValueAt(tabelaPessoas.getSelectedRow(), 0);
                    model.removeRow(tabelaPessoas.getSelectedRow());
                    System.out.println(user);
                    try {
                        agenda.remover(user);
//                    Persistencia.convertListToXML(agenda.listarContatos());
                    } catch (ContatoNaoEncontradoException | ParametroVazioException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }
                } catch (Exception e) {

                }
                listarNaTabela();
            }
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnTelaRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaRemoverActionPerformed
        painelListar.setVisible(true);
        painelCadastro.setVisible(false);
        painelInicio.setVisible(false);
        painelBuscar.setVisible(false);
        painelTotalizadores.setVisible(false);
        btnRemover.setVisible(true);
        btnListar.setVisible(false);
//        txtRemover.setVisible(true);
        lblTituloListaRemove.setText("Remover Pessoas");
    }//GEN-LAST:event_btnTelaRemoverActionPerformed

    private void btnTelaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaTotalActionPerformed
        painelTotalizadores.setVisible(true);
        painelCadastro.setVisible(false);
        painelInicio.setVisible(false);
        painelListar.setVisible(false);
        painelBuscar.setVisible(false);
    }//GEN-LAST:event_btnTelaTotalActionPerformed

    private void btnListarTotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTotActionPerformed
        lblListarTot.setText(agenda.quantidadePessoas() + " e " + agenda.quantidade() + " pessoas no total");
    }//GEN-LAST:event_btnListarTotActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        painelInicio.setVisible(true);
        painelCadastro.setVisible(false);
        painelListar.setVisible(false);
        painelBuscar.setVisible(false);
        painelTotalizadores.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnListarTot;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnResultadoBuscar;
    private javax.swing.JButton btnTelaBuscar;
    private javax.swing.JButton btnTelaCadastro;
    private javax.swing.JButton btnTelaListar;
    private javax.swing.JButton btnTelaRemover;
    private javax.swing.JButton btnTelaTotal;
    private javax.swing.ButtonGroup buttonGroupPessoaFisicaJuridica;
    private javax.swing.JComboBox<String> comboBoxEstados;
    private javax.swing.JFormattedTextField formattedTxtCnpj;
    private javax.swing.JFormattedTextField formattedTxtCpf;
    private javax.swing.JFormattedTextField formattedTxtTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListarTot;
    private javax.swing.JLabel lblResultadoBuscar;
    private javax.swing.JLabel lblTituloListaRemove;
    private javax.swing.JPanel painelBuscar;
    private javax.swing.JPanel painelCadastro;
    private javax.swing.JPanel painelInicio;
    private javax.swing.JPanel painelListar;
    private javax.swing.JPanel painelTotalizadores;
    private javax.swing.JPanel painelTxtFieldGroup;
    private javax.swing.JRadioButton radioBtnPf;
    private javax.swing.JRadioButton radioBtnPj;
    private javax.swing.JTable tabelaPessoas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtRazaoSocial;
    // End of variables declaration//GEN-END:variables
}
